version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: britespot
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: auth-service
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/britespot
      - JWT_SECRET=britespot_prod_secret
    depends_on:
      - db

  router-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: router-service
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/britespot
    depends_on:
      - db

  billing-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: billing-service
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/britespot
      - ROUTER_SERVICE_URL=http://router-service:3000
    depends_on:
      - db
      - router-service

  mpesa-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: mpesa-service
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/britespot

  commission-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: commission-service
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/britespot

  notification-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: notification-service
    environment:
      - AT_API_KEY=atsk_0dd832dd0e6751d7e60f5fda75ee72e8f034c9eee7fdb25d6f5e3baaf0d45981128af5cb
      - MAILTRAP_TOKEN=4770f2e371a31288d8c725e9bf204e60

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile.nest
      args:
        SERVICE_NAME: analytics-service
    environment:
      - DATABASE_URL=postgresql://root:password@db:5432/britespot

  # FRONTENDS
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.next
      args:
        APP_NAME: dashboard
    ports:
      - "3000:3000"

  captive-portal:
    build:
      context: .
      dockerfile: Dockerfile.next
      args:
        APP_NAME: captive-portal
    ports:
      - "3001:3000"

  admin-panel:
    build:
      context: .
      dockerfile: Dockerfile.next
      args:
        APP_NAME: admin-panel
    ports:
      - "3002:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - router-service
      - billing-service
      - mpesa-service
      - dashboard
