worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    upstream dashboard { server dashboard:3000; }
    upstream portal { server captive-portal:3000; }
    upstream auth { server auth-service:3000; }
    upstream billing { server billing-service:3000; }
    upstream mpesa { server mpesa-service:3000; }

    server {
        listen 80;
        server_name localhost;

        # Next.js Frontends
        location / {
            proxy_pass http://dashboard;
            proxy_set_header Host $host;
        }

        location /portal/ {
            proxy_pass http://portal;
            proxy_set_header Host $host;
        }

        # NestJS Backend Microservices
        location /api/auth/ {
            proxy_pass http://auth/;
            proxy_set_header Host $host;
        }

        location /api/billing/ {
            proxy_pass http://billing/;
            proxy_set_header Host $host;
        }

        location /api/mpesa/ {
            proxy_pass http://mpesa/;
            proxy_set_header Host $host;
        }
    }
}
